---
driver:
 name: vagrant

provisioner:
 name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: a
    run_list:
      - recipe[a::default]
  - name: b
    run_list:
      - recipe[b::default]
  - name: c
    run_list:
      - recipe[c::default]
